name: unit-tests
run-name: Unit Test Action
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
jobs:
  run-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: udpate packages
        run: sudo apt-get update -y
      - name: install googletest
        run: sudo apt-get install libgtest-dev
      - name: autoreconf
        run: cd code && autoreconf -vfi
      - name: configure
        run: cd code && ./configure
      - name: build
        run: cd code && make -j 4
      - name: test
        run: code/src/test
